name: majestic_rooms
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  supabase_flutter: ^2.14.0
  get: ^4.7.3
  cached_network_image: ^3.4.1

  # UI
  fluttertoast: ^9.1.0
  shimmer: ^3.0.0
  flutter_multiple_loaders: ^1.1.1
  photo_view: ^0.15.0
  share_plus: ^13.2.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10

  # Maps implementation
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/launcher/

  fonts:
    - family: Fustat
      fonts:
        - asset: assets/fonts/Fustat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Fustat-Light.ttf
          weight: 300
        - asset: assets/fonts/Fustat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fustat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fustat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fustat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fustat-ExtraBold.ttf
          weight: 800



flutter_native_splash:
  color: "#F9F9FA"
  image: "assets/launcher/splash.png"
  color_dark: "#111111"
  image_dark: "assets/launcher/splash_dark.png"
  android_12:
    image: "assets/launcher/splash.png"
    image_dark: "assets/launcher/splash_dark.png"
    color: "#F9F9FA"
    color_dark: "#111111"
  android: true
  ios: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launcher/icon_adaptive.png"
