const Map<String, String> arSA = {
  'About': 'حول',
  'After 02:00 PM': 'بعد 02:00 مساءً',
  'Already have an account? ': 'هل لديك حساب بالفعل؟ ',
  'Apply': 'تطبيق',
  'Are you sure you want to go back? Your room selections and dates will be reset.': 'هل أنت متأكد من رغبتك في العودة؟ ستتم إعادة تعيين اختيارات غرفتك والتواريخ.',
  'Are you sure you want to remove this hotel from your saved list?': 'هل أنت متأكد أنك تريد إزالة هذا الفندق من قائمتك المحفوظة؟',
  'Before 11:00 AM': 'قبل 11:00 صباحاً',
  'Cancel': 'إلغاء',
  'Cancel Booking': 'إلغاء الحجز',
  'Cancel Booking?': 'إلغاء الحجز؟',
  'Check Availability': 'التحقق من التوفر',
  'CHECK-IN': 'تسجيل الدخول',
  'CHECK-OUT': 'تسجيل الخروج',
  'City View': 'إطلالة على المدينة',
  'Close': 'إغلاق',
  'Create new account': 'إنشاء حساب جديد',
  'Create your account': 'أنشئ حسابك',
  'Discard': 'تجاهل',
  'Discard Selections?': 'تجاهل الاختيارات؟',
  'Discount': 'خصم',
  'DURATION': 'المدة',
  'Edit': 'تعديل',
  'Error: @e': 'خطأ: @e',
  'EUR (€)': 'يورو (€)',
  'Forgot Password?': 'هل نسيت كلمة المرور؟',
  'HOTEL': 'الفندق',
  'Keep Booking': 'الاحتفاظ بالحجز',
  'Keep Editing': 'الاستمرار في التعديل',
  'Logout': 'تسجيل الخروج',
  '/night': '/ليلة',
  ' /night': ' /ليلة',
  'No Notifications': 'لا توجد إشعارات',
  'No saved hotels': 'لا توجد فنادق محفوظة',
  'Notifications': 'الإشعارات',
  'OK': 'موافق',
  'Price Details': 'تفاصيل السعر',
  'Remove': 'إزالة',
  'Remove from saved': 'إزالة من المحفوظات',
  'ROOMS': 'الغرف',
  'SAR (SAR)': 'ريال سعودي (SAR)',
  'Save': 'حفظ',
  'Saved to gallery!': 'تم الحفظ في المعرض!',
  'Save to Gallery': 'حفظ في المعرض',
  'Select Currency': 'اختر العملة',
  'Select Language': 'اختر اللغة',
  'Share': 'مشاركة',
  'Sign In Again': 'تسجيل الدخول مرة أخرى',
  'Stay Dates': 'تواريخ الإقامة',
  'Stay Details': 'تفاصيل الإقامة',
  'Subtotal': 'المجموع الفرعي',
  'Total Paid': 'الإجمالي المدفوع',
  'Update Password': 'تحديث كلمة المرور',
  'USD (\$)': 'دولار أمريكي (\$)',
  'Welcome back': 'مرحباً بعودتك',
  'Welcome back  ': 'مرحباً بعودتك  ',
  'Night': 'ليلة',
  'Nights': 'ليالِ',
  'Language': 'اللغة',
  'English': 'الإنجليزية',
  'Arabic': 'العربية',
  'Clear All Bookings (Debug)': 'مسح جميع الحجوزات',
  'Version: @version': 'الإصدار: @version',
  'Update @title': 'تحديث @title',
  'about_description': 'نجعل العثور على الفنادق في المملكة العربية السعودية أمرًا سهلاً. تساعد منصتنا المسافرين على حجز إقامات رائعة، من الغرف المريحة إلى الفنادق الفاخرة، في جميع أنحاء المملكة.',
  'our_story_title': 'قصتنا',
  'our_story_content': 'بدأت MajesticRooms في عام 2023 من قبل مجموعة من محبي السفر السعوديين، بهدف جعل حجز الفنادق بسيطًا. رأينا الكثير من المواقع القديمة وأردنا إنشاء مكان واحد حيث يمكن للناس العثور على فنادق موثوقة في المملكة العربية السعودية، من شوارع الرياض المزدحمة إلى شواطئ جدة الهادئة. الآن، نساعد آلاف المسافرين في العثور على إقامتهم المثالية.',
  'our_mission_title': 'مهمتنا',
  'our_mission_content': 'هدفنا هو جعل حجز الفنادق في المملكة العربية السعودية سلسًا وموثوقًا. نريد أن يتمكن المسافرون من العثور بسهولة على الفنادق التي تناسب احتياجاتهم، سواء كانوا يزورون مكة المكرمة، أو يستكشفون العلا، أو يعملون في الدمام. نحن نركز على المعلومات الواضحة، وسهولة التصفح، ودعم الفنادق المحلية لمشاركة أجوائها الفريدة.',
  'our_values_title': 'قيمنا',
  'value_trust_title': 'الثقة والشفافية',
  'value_trust_content': 'أسعار صادقة، معلومات واضحة، وعلاقات دائمة مع الضيوف وشركاء الفنادق.',
  'value_customer_title': 'العميل أولاً',
  'value_customer_content': 'رضاك هو أولويتنا. الدعم متاح على مدار الساعة طوال أيام الأسبوع لأي استفسارات.',
  'value_passion_title': 'شغف السفر',
  'value_passion_content': 'نحن نتفهم متعة السفر ونعمل بلا كلل لجعل كل رحلة لا تُنسى.',
  'value_simplicity_title': 'البساطة',
  'value_simplicity_content': 'منصتنا بديهية وسهلة الاستخدام، مما يجعل حجز الفنادق أمرًا في غاية السهولة.',
  'value_security_title': 'الأمان والخصوصية',
  'value_security_content': 'تتم حماية بياناتك ومعلومات الدفع الخاصة بك من خلال إجراءات أمنية رائدة في الصناعة.',
  'value_expertise_title': 'الخبرة المحلية',
  'value_expertise_content': 'تساعدنا معرفتنا العميقة بالمملكة العربية السعودية في التوصية بأفضل الفنادق للحجاج والمسافرين على حد سواء.',
  'licensed_company': 'شركة مرخصة',
  'license_number': 'وزارة السياحة — رقم 73105591',
  'terms_of_service': 'شروط الخدمة',
  'privacy_policy': 'سياسة الخصوصية',
  'contact_us': 'اتصل بنا',
  'call_us': 'اتصل بنا',
  'copyright_text': '© 2026 Majestic Rooms. جميع الحقوق محفوظة.',
  'User Settings': 'إعدادات المستخدم',
  'My Bookings': 'حجوزاتي',
  'Saved Hotels': 'الفنادق المحفوظة',
  'Contact Support': 'التواصل مع الدعم',
  'Helpline': 'خط المساعدة',
  'Settings': 'الإعدادات',
  'Log Out': 'تسجيل الخروج',
  'Preferences': 'التفضيلات',
  'could_not_open_link': 'تعذر فتح الرابط',
  'no_email_app_found': 'لم يتم العثور على تطبيق بريد إلكتروني',
  'no_phone_app_found': 'لم يتم العثور على تطبيق هاتف',
  'app_name_text': 'اسم التطبيق: @appName',
  'Enter new @title': 'أدخل @title الجديد',
  'Personal Information': 'المعلومات الشخصية',
  'Full Name': 'الاسم الكامل',
  'Set name': 'تعيين الاسم',
  'Email': 'البريد الإلكتروني',
  'Set email': 'تعيين البريد الإلكتروني',
  'Phone Number': 'رقم الهاتف',
  'Update phone': 'تحديث الهاتف',
  'Password': 'كلمة المرور',
  'Delete Account': 'حذف الحساب',
  'Name': 'الاسم',
  'Phone': 'الهاتف',
  'Choose a strong password': 'اختر كلمة مرور قوية',
  'password_desc': 'استخدم كلمة مرور طويلة وعشوائية لا تستخدمها في أي مكان آخر للحفاظ على أمان حسابك.',
  'Current Password': 'كلمة المرور الحالية',
  'Enter current password': 'أدخل كلمة المرور الحالية',
  'Current password is required': 'كلمة المرور الحالية مطلوبة',
  'New Password': 'كلمة المرور الجديدة',
  'Enter new password': 'أدخل كلمة المرور الجديدة',
  'New password is required': 'كلمة المرور الجديدة مطلوبة',
  'Must be at least 6 characters': 'يجب أن تتكون من 6 أحرف على الأقل',
  'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
  'Re-type new password': 'أعد كتابة كلمة المرور الجديدة',
  'Passwords do not match': 'كلمتا المرور غير متطابقتين',
  'Weak': 'ضعيفة',
  'Medium': 'متوسطة',
  'Strong': 'قوية',
  'Password updated': 'تم تحديث كلمة المرور',
  'Your password has been changed successfully.': 'تم تغيير كلمة المرور الخاصة بك بنجاح.',
  'Sign In Failed': 'فشل تسجيل الدخول',
  'Success': 'نجاح',
  'Update Failed': 'فشل التحديث',
  'Invalid Password': 'كلمة مرور غير صالحة',
  'Action Denied': 'الإجراء مرفوض',
  'Error': 'خطأ',
  'Debug': 'تصحيح',
  'Local Mode': 'الوضع المحلي',
  'Booking Cancelled': 'تم إلغاء الحجز',
  'Profile photo updated successfully.': 'تم تحديث صورة الملف الشخصي بنجاح.',
  'Could not update profile photo.': 'تعذر تحديث صورة الملف الشخصي.',
  'Name updated successfully.': 'تم تحديث الاسم بنجاح.',
  'Could not update name.': 'تعذر تحديث الاسم.',
  'Email updated successfully. Please verify your new email.': 'تم تحديث البريد الإلكتروني بنجاح. يرجى التحقق من بريدك الجديد.',
  'Could not update email.': 'تعذر تحديث البريد الإلكتروني.',
  'Password must be at least 6 characters.': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
  'Password updated successfully.': 'تم تحديث كلمة المرور بنجاح.',
  'Could not update password.': 'تعذر تحديث كلمة المرور.',
  'Phone number updated successfully.': 'تم تحديث رقم الهاتف بنجاح.',
  'Could not update phone number.': 'تعذر تحديث رقم الهاتف.',
  'Cannot delete this account.': 'لا يمكن حذف هذا الحساب.',
  'Explore': 'استكشف',
  'Saved': 'المحفوظات',
  'Bookings': 'الحجوزات',
  'Profile': 'الملف الشخصي',
  'No hotels to show': 'لا توجد فنادق لعرضها',
  'result_found': 'تم العثور على نتيجة @count',
  'results_found': 'تم العثور على @count نتائج',
  'Search hotels, resorts...': 'ابحث عن فنادق، منتجعات...',
  'A City on Planet Earth': 'مدينة على كوكب الأرض',
  'Mecca': 'مكة',
  'Medina': 'المدينة',
  'Jeddah': 'جدة',
  'Riyadh': 'الرياض',
  'Khobar': 'الخبر',
  'Dhahran': 'الظهران',
  'Abha': 'أبها',
  'Starting from': 'تبدأ من',
  'licence_no': 'رقم الترخيص: @no',
  'No licence number provided': 'لم يتم توفير رقم الترخيص',
  'In a Galaxy far away': 'في مجرة بعيدة',
  'No description given': 'لا يوجد وصف',
  'Services': 'الخدمات',
  'Location': 'الموقع',
  'km_from_haram': '@km كم من الحرم',
  'Policies': 'السياسات',
  'Standard terms & conditions apply': 'تطبق الشروط والأحكام القياسية',
  'Reviews': 'التقييمات',
  'No reviews yet.': 'لا توجد تقييمات بعد.',
  'Special Offer!': 'عرض خاص!',
  'discount_off': 'خصم @discount%',
  'use_code': 'استخدم الرمز "@code" عند الدفع.',
  'valid_until': 'صالح حتى @date',
  'Open in Maps': 'افتح في الخرائط',
  'share_hotel': 'تفقد @hotel على غرف ماجستيك!\n\n@address\n\n@url',
  'review_count': '·  @count تقييم',
  'reviews_count': '·  @count تقييمات',
  'Air Conditioner': 'تكييف',
  'Accessibility': 'سهولة الوصول',
  'Coffee Shop': 'مقهى',
  'Club': 'نادي',
  'Cards Accepted': 'بطاقات مقبولة',
  'Shuttle Bus Service': 'خدمة النقل بالحافلة',
  'Swimming Pool': 'مسبح',
  'Elevator': 'مصعد',
  'Fitness Center': 'مركز لياقة بدنية',
  'Restaurant': 'مطعم',
  'Wi-Fi Internet': 'إنترنت واي فاي',
  'Press back again to exit': 'اضغط للرجوع مرة أخرى للخروج',
  'Search your saved hotels': 'البحث في فنادقك المحفوظة',
  'Search query cannot be empty': 'لا يمكن أن يكون استعلام البحث فارغًا',
  'No hotels found': 'لم يتم العثور على فنادق',
  'error_with_message': 'خطأ: @message',
  'Could not fetch reviews': 'تعذر جلب التقييمات',
  'Failed to confirm booking.': 'فشل تأكيد الحجز.',
  'Local bookings cleared (No user logged in).': 'تم مسح الحجوزات المحلية (لم يتم تسجيل دخول أي مستخدم).',
  'All bookings completely deleted from backend and app.': 'تم حذف جميع الحجوزات تمامًا من الخادم والتطبيق.',
  'failed_to_delete_bookings_error': 'فشل حذف الحجوزات: @error',
  'Hotel does not exist on the server. Proceeding in local mode.': 'الفندق غير موجود على الخادم. المتابعة في الوضع المحلي.',
  'Hotel does not exist on the server. Booking cancelled locally.': 'الفندق غير موجود على الخادم. تم إلغاء الحجز محليًا.',
  'Your booking has been successfully cancelled.': 'تم إلغاء حجزك بنجاح.',
  'Failed to cancel booking. Please try again.': 'فشل إلغاء الحجز. يرجى المحاولة مرة أخرى.',
};
