const Map<String, String> enUS = {
  'About': 'About',
  'After 02:00 PM': 'After 02:00 PM',
  'Already have an account? ': 'Already have an account? ',
  'Apply': 'Apply',
  'Are you sure you want to go back? Your room selections and dates will be reset.':
      'Are you sure you want to go back? Your room selections and dates will be reset.',
  'Are you sure you want to remove this hotel from your saved list?':
      'Are you sure you want to remove this hotel from your saved list?',
  'Before 11:00 AM': 'Before 11:00 AM',
  'Cancel': 'Cancel',
  'Cancel Booking': 'Cancel Booking',
  'Cancel Booking?': 'Cancel Booking?',
  'Check Availability': 'Check Availability',
  'CHECK-IN': 'CHECK-IN',
  'CHECK-OUT': 'CHECK-OUT',
  'City View': 'City View',
  'Close': 'Close',
  'Create new account': 'Create new account',
  'Create your account': 'Create your account',
  'Discard': 'Discard',
  'Discard Selections?': 'Discard Selections?',
  'Discount': 'Discount',
  'DURATION': 'DURATION',
  'Edit': 'Edit',
  'Error: @e': 'Error: @e',
  'EUR (€)': 'EUR (€)',
  'Forgot Password?': 'Forgot Password?',
  'HOTEL': 'HOTEL',
  'Keep Booking': 'Keep Booking',
  'Keep Editing': 'Keep Editing',
  'Logout': 'Logout',
  '/night': '/night',
  ' /night': ' /night',
  ' / night': ' / night',
  'No Notifications': 'No Notifications',
  'No saved hotels': 'No saved hotels',
  'Notifications': 'Notifications',
  'OK': 'OK',
  'Price Details': 'Price Details',
  'Remove': 'Remove',
  'Remove from saved': 'Remove from saved',
  'ROOMS': 'ROOMS',
  'SAR (SAR)': 'SAR (SAR)',
  'Save': 'Save',
  'Saved to gallery!': 'Saved to gallery!',
  'Save to Gallery': 'Save to Gallery',
  'Currency': 'Currency',
  'Select Currency': 'Select Currency',
  'Select Language': 'Select Language',
  'Share': 'Share',
  'Sign In Again': 'Sign In Again',
  'Stay Dates': 'Stay Dates',
  'Stay Details': 'Stay Details',
  'Subtotal': 'Subtotal',
  'Total Paid': 'Total Paid',
  'Update Password': 'Update Password',
  'USD (\$)': 'USD (\$)',
  'Welcome back': 'Welcome back',
  'Welcome back  ': 'Welcome back  ',
  'Night': 'Night',
  'Nights': 'Nights',
  'Language': 'Language',
  'English': 'English',
  'Arabic': 'Arabic',
  'Clear All Bookings (Debug)': 'Clear All Bookings (Debug)',
  'Version: @version': 'Version: @version',
  'Update @title': 'Update @title',
  'about_description':
      'We make finding hotels in Saudi Arabia easy. Our platform helps travelers book great stays, from cozy rooms to luxury hotels, all across the Kingdom.',
  'our_story_title': 'Our Story',
  'our_story_content':
      'Started in 2023 by a group of Saudi travel lovers, MajesticRooms began with a goal to make hotel booking simple. We saw too many outdated websites and wanted to create one place where people could find trusted hotels in Saudi Arabia, from Riyadh\'s busy streets to Jeddah\'s calm beaches. Now, we help thousands of travelers find their perfect stay.',
  'our_mission_title': 'Our Mission',
  'our_mission_content':
      'Our goal is to make hotel booking in Saudi Arabia smooth and reliable. We want travelers to easily find hotels that match their needs, whether they\'re visiting Mecca, exploring Al-Ula, or working in Dammam. We focus on clear information, easy navigation, and supporting local hotels to share their unique vibe.',
  'our_values_title': 'Our Values',
  'value_trust_title': 'Trust & Transparency',
  'value_trust_content':
      'Honest pricing, clear information, and lasting relationships with guests and hotel partners.',
  'value_customer_title': 'Customer First',
  'value_customer_content':
      'Your satisfaction is our priority. Support is available 24/7 for any queries.',
  'value_passion_title': 'Passion for Travel',
  'value_passion_content':
      'We understand the joy of travel and work tirelessly to make every journey memorable.',
  'value_simplicity_title': 'Simplicity',
  'value_simplicity_content':
      'Our platform is intuitive and easy to use, making hotel booking a breeze.',
  'value_security_title': 'Security & Privacy',
  'value_security_content':
      'Your data and payment information are protected with industry-leading security measures.',
  'value_expertise_title': 'Local Expertise',
  'value_expertise_content':
      'Our deep knowledge of Saudi Arabia helps us recommend the best hotels for pilgrims and travelers alike.',
  'licensed_company': 'Licensed Company',
  'license_number': 'Ministry of Tourism — No. 73105591',
  'terms_of_service': 'Terms of Service',
  'privacy_policy': 'Privacy Policy',
  'contact_us': 'Contact Us',
  'call_us': 'Call Us',
  'copyright_text': '© 2026 Majestic Rooms. All rights reserved.',
  'User Settings': 'User Settings',
  'My Bookings': 'My Bookings',
  'Saved Hotels': 'Saved Hotels',
  'Contact Support': 'Contact Support',
  'Helpline': 'Helpline',
  'Settings': 'Settings',
  'Log Out': 'Log Out',
  'Preferences': 'Preferences',
  'could_not_open_link': 'Could not open link',
  'no_email_app_found': 'No email app found',
  'no_phone_app_found': 'No phone app found',
  'app_name_text': 'App Name: @appName',
  'Enter new @title': 'Enter new @title',
  'Personal Information': 'Personal Information',
  'Full Name': 'Full Name',
  'Set name': 'Set name',
  'Email': 'Email',
  'Set email': 'Set email',
  'Phone Number': 'Phone Number',
  'Update phone': 'Update phone',
  'Password': 'Password',
  'Delete Account': 'Delete Account',
  'Name': 'Name',
  'Phone': 'Phone',
  'Choose a strong password': 'Choose a strong password',
  'password_desc':
      'Use a long, random password you don\'t use anywhere else to keep your account secure.',
  'Current Password': 'Current Password',
  'Enter current password': 'Enter current password',
  'Current password is required': 'Current password is required',
  'New Password': 'New Password',
  'Enter new password': 'Enter new password',
  'New password is required': 'New password is required',
  'Must be at least 6 characters': 'Must be at least 6 characters',
  'Confirm New Password': 'Confirm New Password',
  'Re-type new password': 'Re-type new password',
  'Passwords do not match': 'Passwords do not match',
  'Weak': 'Weak',
  'Medium': 'Medium',
  'Strong': 'Strong',
  'Password updated': 'Password updated',
  'Your password has been changed successfully.':
      'Your password has been changed successfully.',
  'Sign In Failed': 'Sign In Failed',
  'Success': 'Success',
  'Update Failed': 'Update Failed',
  'Invalid Password': 'Invalid Password',
  'Action Denied': 'Action Denied',
  'Error': 'Error',
  'Debug': 'Debug',
  'Local Mode': 'Local Mode',
  'Booking Cancelled': 'Booking Cancelled',
  'Profile photo updated successfully.': 'Profile photo updated successfully.',
  'Could not update profile photo.': 'Could not update profile photo.',
  'Name updated successfully.': 'Name updated successfully.',
  'Could not update name.': 'Could not update name.',
  'Email updated successfully. Please verify your new email.':
      'Email updated successfully. Please verify your new email.',
  'Could not update email.': 'Could not update email.',
  'Password must be at least 6 characters.':
      'Password must be at least 6 characters.',
  'Password updated successfully.': 'Password updated successfully.',
  'Could not update password.': 'Could not update password.',
  'Phone number updated successfully.': 'Phone number updated successfully.',
  'Could not update phone number.': 'Could not update phone number.',
  'Cannot delete this account.': 'Cannot delete this account.',
  'Explore': 'Explore',
  'Saved': 'Saved',
  'Bookings': 'Bookings',
  'Profile': 'Profile',
  'No hotels to show': 'No hotels to show',
  'result_found': '@count result found',
  'results_found': '@count results found',
  'Search hotels, resorts...': 'Search hotels, resorts...',
  'A City on Planet Earth': 'A City on Planet Earth',
  'Mecca': 'Mecca',
  'Medina': 'Medina',
  'Jeddah': 'Jeddah',
  'Riyadh': 'Riyadh',
  'Khobar': 'Khobar',
  'Dhahran': 'Dhahran',
  'Abha': 'Abha',
  'Starting from': 'Starting from',
  'licence_no': 'Licence no: @no',
  'No licence number provided': 'No licence number provided',
  'In a Galaxy far away': 'In a Galaxy far away',
  'No description given': 'No description given',
  'Services': 'Services',
  'Location': 'Location',
  'km_from_haram': '@km KM from the Haram',
  'Policies': 'Policies',
  'Standard terms & conditions apply': 'Standard terms & conditions apply',
  'Reviews': 'Reviews',
  'No reviews yet.': 'No reviews yet.',
  'Special Offer!': 'Special Offer!',
  'discount_off': '@discount% OFF',
  'use_code': 'Use code "@code" at checkout.',
  'valid_until': 'Valid until @date',
  'Open in Maps': 'Open in Maps',
  'share_hotel': 'Check out @hotel on Majestic Rooms!\n\n@address\n\n@url',
  'review_count': '·  @count review',
  'reviews_count': '·  @count reviews',
  'Air Conditioner': 'Air Conditioner',
  'Accessibility': 'Accessibility',
  'Coffee Shop': 'Coffee Shop',
  'Club': 'Club',
  'Cards Accepted': 'Cards Accepted',
  'Shuttle Bus Service': 'Shuttle Bus Service',
  'Swimming Pool': 'Swimming Pool',
  'Elevator': 'Elevator',
  'Fitness Center': 'Fitness Center',
  'Restaurant': 'Restaurant',
  'Wi-Fi Internet': 'Wi-Fi Internet',
  'Free WiFi': 'Free WiFi',
  'Concierge': 'Concierge',
  'Standard terms and conditions apply.': 'Standard terms and conditions apply.',
  'Prayer Room': 'Prayer Room',
  'Business Center': 'Business Center',
  'Room Service': 'Room Service',
  'Airport Shuttle': 'Airport Shuttle',
  'Parking': 'Parking',
  'Family Rooms': 'Family Rooms',
  'Standard Room': 'Standard Room',
  'Room': 'Room',
  'bed_count': '@count Bed',
  'beds_count': '@count Beds',
  'Select Rooms': 'Select Rooms',
  'Book Now': 'Book Now',
  'Error: @error': 'Error: @error',
  'Booking Confirmed!': 'Booking Confirmed!',
  'reservation_confirmed': 'Your reservation at @hotel is confirmed.\\nCheck your Bookings tab for full details.',
  'night_count': '@count Night',
  'nights_count': '@count Nights',
  'TOTAL PAID': 'TOTAL PAID',
  'Go to Bookings': 'Go to Bookings',
  'Back to Exploring': 'Back to Exploring',
  'Saving...': 'Saving...',
  'Booking Summary': 'Booking Summary',
  'room_count': '@count Room',
  'rooms_count': '@count Rooms',
  'Cancellation Policy': 'Cancellation Policy',
  'Cancelled': 'Cancelled',
  'Paid': 'Paid',
  'Booking...': 'Booking...',
  'Confirm Booking': 'Confirm Booking',
  'Total price': 'Total price',
  'cancel_booking_desc': 'Are you sure you want to cancel this booking? Cancelling a booking may incur extra charges depending on the hotel policy.',
  'No rooms available': 'No rooms available',
  'with_breakfast': 'With breakfast: @price / night',
  'No information given': 'No information given',
  'Are you sure you want to logout?': 'Are you sure you want to logout?',
  'You will be taken back to the login screen.': 'You will be taken back to the login screen.',
  'Press back again to exit': 'Press back again to exit',
  'Search your saved hotels': 'Search your saved hotels',
  'Search query cannot be empty': 'Search query cannot be empty',
  'No hotels found': 'No hotels found',
  'error_with_message': 'Error: @message',
  'Could not fetch reviews': 'Could not fetch reviews',
  'Failed to confirm booking.': 'Failed to confirm booking.',
  'Local bookings cleared (No user logged in).':
      'Local bookings cleared (No user logged in).',
  'All bookings completely deleted from backend and app.':
      'All bookings completely deleted from backend and app.',
  'failed_to_delete_bookings_error': 'Failed to delete bookings: @error',
  'Hotel does not exist on the server. Proceeding in local mode.':
      'Hotel does not exist on the server. Proceeding in local mode.',
  'Hotel does not exist on the server. Booking cancelled locally.':
      'Hotel does not exist on the server. Booking cancelled locally.',
  'Your booking has been successfully cancelled.':
      'Your booking has been successfully cancelled.',
  'Failed to cancel booking. Please try again.':
      'Failed to cancel booking. Please try again.',
  'Selected Rooms': 'Selected Rooms',
  'Room @number': 'Room @number',
  'Service fee': 'Service fee',
  'Occupancy taxes': 'Occupancy taxes',
  'Total': 'Total',
  'rooms_nights_calc': '@rooms room(s) × @nights night(s)',
  'Tap to select': 'Tap to select',
  'From': 'From',
  'To': 'To',
  'Not selected': 'Not selected',
  'free_cancellation_fallback': 'Free cancellation before check-in date. Review our full terms before confirming.',
  'nights_rooms_dot': '@nights Night(s) · @rooms Room(s)',
  'Pending': 'Pending',
  'Confirmed': 'Confirmed',
  'Checked In': 'Checked In',
  'Completed': 'Completed',
  'No bookings yet': 'No bookings yet',
  'Your confirmed reservations will appear here.': 'Your confirmed reservations will appear here.',
  'No reservations match this filter.': 'No reservations match this filter.',
};
